### ISSUE TITLE
Translation doesn't work

### ISSUE THREAD

**Issue by KashTan220** [tsquez/wp-starter#1]
Hi.
Thank you for theme. I'm trying to translate some of it, but I have a problem. When I put the 'pl_PL.mo' and 'pl_PL.po' files in the 'wp-starter/language/' folder, translation doesn't work. When the files are in the parent theme folder ('wp-forge/language/'), translation works like it should. I'm translating 'wpforge-en_US.po' file in Poedit. Doesn't it work, because I'm using parent theme language file? But what should I do to make it work?
Thanks for your help.

**Comment by tsquez** [comment]
Hi Kash,

All I did was use the following resource when I released WP-Starter: https://codex.wordpress.org/Function_Reference/load_child_theme_textdomain - I only speak English (well Spanish to but not enough to use it on a site) so I have never really had to use translation files.

I did however do a Google search and found the following resource for you. I think this one may help: http://ronangelo.com/add-language-files-on-a-wordpress-child-theme/ - I believe this may help you. Please let me know if you get this fixed and what you did :sunglasses:

**Comment by KashTan220** [comment]
It works! :D 
All I had to do was to replace `load_child_theme_textdomain( 'wpstarter', get_stylesheet_directory() . '/language' );` with `load_child_theme_textdomain( 'wpforge', get_stylesheet_directory() . '/language' );` in `functions.php`. It's confusing because WP Codex says that there has to be "child theme's name", but tutorial provided by you says it has to be "parent theme's name". Anyway it works now. Thank you very much, tsquez :)

**Comment by tsquez** [comment]
AWESOME!...Glad it worked out for you. I'll make the change to WP-Starter as well so no one else runs into this issue.

Glad you like the theme :-)

via my phone

**Comment by KashTan220** [comment]
Thanks for help. It's great theme :)

**Comment by tsquez** [comment]
Anytime amigo and thank you

via my phone
