### ISSUE TITLE
Minor Correction - WordPress License

### ISSUE THREAD

**Issue by Techdoode** [tsquez/wp-starter#2]
This is a minor typo correction.

The License section of README.md has the following:

"WordPress is GPLv2 - http://www.gnu.org/licenses/gpl-2.1.html"

That link is broken.  You may have meant to link to http://www.gnu.org/licenses/gpl-2.0.html

However, might it suffice to link to https://wordpress.org/about/license/?  Linking to the WordPress page will pick up future changes made to their wording.

**Comment by tsquez** [comment]
Hi Nick,

Thanks for pointing that out to me. Its actually supposed to be the same as WP-Forge: http://www.gnu.org/licenses/gpl-2.0.html

I forget what I was doing...lol. Anyway WP-Starter was assigned a reviewer today overr at WordPress.org. - and if you saw this mistake I am sure they will see it as well....lol no worries though amigo, this is how we keep things on the up and up.

Thank you again sir your assitanceis greatly appreciated :wink:

**Comment by Techdoode** [comment]
My pleasure.  :-)
