### ISSUE TITLE
Custom Top Menu nav bar?

### ISSUE THREAD

**Issue by COLABORATI** [tsquez/wp-starter#4]
Hi, very nice (sub-) theme! Would you like to give me some hints for a custom menu, this would be very appreciated:
- how to add the site identity logo to the menu "home" area on the left (currently only the site identity text is there, but no logo - a logo jpg is set in customizer)?
- how to center the top menu content?
- how to change the dropdowns to a 100% width submenu with different colors that is visible only while mouseover (+ slideup and slidedown animations, please)?
- how to add a search box to the right end of the top menu?

I have found several instructions for F5, however I am not sure if these can be added to the child theme and in which way? yes, I have most of the pieces, I just do not yet understand how to put them into a wp-forge child-theme. Can this be done with just some added lines to some css / sass file or do I have to modify the wp_nav_menu walker? 

To get it to the next level: can the options mentioned above be added to the customizer of the child theme or should it go to the customizer of the parent wp-forge? 

Yes, sorry, I know, the best way is studying F5 and your wp-forge implementation in all details, I will do this, I swear, however I just hit a brick wall with another theme framework and I am considering switching to foundation "on the fly", everything is great, much better than anything else, but I need a quick fix for the menu right now and then I could go with F5 and kick the other bastard... I was such an idiot not using F5 right from the beginning, I knew it would be a much better option in the long run... well...  

Thank you very much for your attention and this great F5 wp theme!!!

**Comment by tsquez** [comment]
Hey there,

Glad you like the theme. Im sorry you hit a brick wall but unfortunately what you are asking is very involved and time consuming. I do not offer support for "how tos" as I have other things to do. I only offer support if the the theme is not working properly and from what you described your asking for enhancements, which are not provided. Sorry again.

**Comment by COLABORATI** [comment]
Hi, well, maybe you misunderstood me, sorry for my bad english - I just wanted to know how to implement the things I described into your theme - as written above, I have most of the pieces working, I just found your theme and wanted to enhance the custsomizer a little without reading every line of code, but, ok, it's not too important, never mind.

**Comment by tsquez** [comment]
hey there amigo,

I understood you perfectly. If you look at what you wrote above every single one of them begins with "how to"...hence the reason your request has nothing to do with support, i.e the menu is not showing, the post thumbnails are showing in the sidebar...etc. 

Your requests above are enhancements or improvements if you will and therefore do not fall under the "support" umbrella. Again I apologize for inconvenience.
