### ISSUE TITLE
wp-starter 4.0?

### ISSUE THREAD

**Issue by badcat** [tsquez/wp-starter#5]
Is WP-Starter 4.0 coming to github?  Or just on your site?  http://themeawesome.com/wordpress-child-theme/

**Comment by tsquez** [comment]
Yes its coming, possibly tomorrow. I have just been really busy, haven't had a chance to get the new version uploaded. I haven't even uploaded the new version of WP-Forge yet...lol. I'll do that tomorrow as well.

**Comment by tsquez** [comment]
New version of WP-Starter has been uploaded amigo
